- name: copy
  synchronize:
    src: "{{ src_dir }}"
    dest: "{{ dest_dir }}"
    rsync_opts:
    - "--exclude=flomina_iac"
    - "--exclude=.git"
    - "--exclude=.gitignore"
    - "--exclude=README.md"
    - "--exclude=flomina_iac@tmp"
  tags:
  - copy_files
